# Generated by Django 5.0.3 on 2024-03-21 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('sex', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('photo', models.FileField(upload_to='')),
                ('passions', models.CharField(max_length=50)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
