# Generated by Django 5.0.3 on 2024-04-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passions_alter_users_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
