# Generated by Django 5.0.3 on 2024-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passions',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
